unique_ids:
  forms:
    ArticleEdit: 75DEUTL4THQSC7KBPCCSIP4NM6DT3ZWL
    ArticleView: SNT334DRC77NMVNEBC6R5CLSTPKY7WD3
    Homepage: WGHIZZZWLM5GBM7X2HI6OSDTKVGCGMZV
  modules: {}
  server_modules:
    ServerModule1: RE7OQJAPRNFR2HKXYIXUWW34FZYCGZQR
  assets:
    standard-page.html: OF24FSTYTCG2KPCQ4Q3LYDHCOMCQUXKS
    theme.css: 7LDBZQ5YNGHEP7OBTWIJCCRIPB7FFQIY
